### ISSUE TITLE
Add image resizing

### ISSUE THREAD

**Issue by Zammer8** [sgalanb/sharepreviews#7]
I am intending to use SharePreviews for a small project that needs other aspect ratios of images, and would like the ability to change the image size when I'm making a template. Is this something that would be possible to add? Thanks!

**Comment by Zammer8** [comment]
@sgalanb

**Comment by sgalanb** [comment]
Hi Zammer! Currently I don't have time to fully implement this, but I've added an option to generate square images (the only other aspect ratio supported by OpenGraph) from a template URL. 

You just need to add the query param `generateSquareImage=true` to any template URL, for example:
https://sharepreviews.com/og/08f36805-dea2-4575-b047-a96c9466d1f4?generateSquareImage=true

To design a square template just add layers normally but think that the maxium X value for any layer is 630px (the image will be 630x630px).

Hope you find this workaround helpful. Regards.
